# Generated by Django 4.1.7 on 2023-02-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='profile',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
